# This CloudFormation template will create:
# + TaskDefinition for a Daemon service running CWAgent
# + ECS TaskRole for permissions to give the DaemonTask
# + TaskExecution role for ECS Agent to reach ECS backend uses policies (CloudWatchAgentServerPolicy and AmazonECSTaskExecutionRolePolicy)
# + ECS Daemon Service 


# name of the cluster where you want to use the CWAgent Daemon Service
Parameters:
  ClusterName:
    Type: String
    Description: Name of the ECS Cluster you want to run CWAgent Daemon Service
  
Resources:

#creating the Task Definition to be used by the Daemon Service
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: cwagent-daemon
      TaskRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/CWAgentECSTaskRole
      ExecutionRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/CWAgentECSExecutionRole
      NetworkMode: bridge
      ContainerDefinitions:
      - Name: cloudwatch-agent
        Image: public.ecr.aws/cloudwatch-agent/cloudwatch-agent:latest
        MountPoints:
        - ReadOnly: true
          ContainerPath: "/rootfs/proc"
          SourceVolume: proc
        - ReadOnly: true
          ContainerPath: "/rootfs/dev"
          SourceVolume: dev
        - ReadOnly: true
          ContainerPath: "/sys/fs/cgroup"
          SourceVolume: al2_cgroup
        - ReadOnly: true
          ContainerPath: "/cgroup"
          SourceVolume: al1_cgroup
        - ReadOnly: true
          ContainerPath: "/rootfs/sys/fs/cgroup"
          SourceVolume: al2_cgroup
        - ReadOnly: true
          ContainerPath: "/rootfs/cgroup"
          SourceVolume: al1_cgroup
        Environment:
        - Name: USE_DEFAULT_CONFIG
          Value: 'True'
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-create-group: 'True'
            awslogs-group: "/ecs/cwagent-daemon"
            awslogs-region:
              Ref: AWS::Region
            awslogs-stream-prefix: ecs
      RequiresCompatibilities:
      - EC2
      Volumes:
      - Name: proc
        Host:
          SourcePath: "/proc"
      - Name: dev
        Host:
          SourcePath: "/dev"
      - Name: al1_cgroup
        Host:
          SourcePath: "/cgroup"
      - Name: al2_cgroup
        Host:
          SourcePath: "/sys/fs/cgroup"
      Cpu: '128'
      Memory: '64'
  ECSDaemonService:
    Type: AWS::ECS::Service
    Properties:
      TaskDefinition:
        Ref: ECSTaskDefinition
      Cluster:
        Ref: ClusterName
      LaunchType: EC2
      SchedulingStrategy: DAEMON
      ServiceName: cwagent-daemon-service
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Allows ECS tasks to call AWS services on your behalf.
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      RoleName: CWAgentECSTaskRole
  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Allows ECS container agent makes calls to the Amazon ECS API on
        your behalf.
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      RoleName: CWAgentECSExecutionRole
